# Generated by Django 5.0.6 on 2024-07-31 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_categoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comentario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateField(default=datetime.datetime.now)),
                (
                    "avaliacao",
                    models.IntegerField(
                        choices=[
                            (1, "1 Estrela"),
                            (2, "2 Estrelas"),
                            (3, "3 Estrelas"),
                            (4, "4 Estrelas"),
                            (5, "5 Estrelas"),
                        ]
                    ),
                ),
                ("comentario", models.TextField()),
            ],
            options={
                "verbose_name": "Comentário",
                "verbose_name_plural": "Comentários",
            },
        ),
        migrations.CreateModel(
            name="Favorito",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_favorite", models.DateField(default=datetime.datetime.now)),
            ],
            options={
                "verbose_name": "Favorito",
                "verbose_name_plural": "Favoritos",
            },
        ),
    ]
