# Generated by Django 5.0.6 on 2024-12-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userprojeto_application_date_userprojeto_is_selected_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telefone",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
