# Generated by Django 5.0.6 on 2024-12-13 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_user_telefone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprojeto",
            name="freelancer_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="candidatos", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
