# Generated by Django 5.0.6 on 2024-08-03 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_user_avatar_user_biografia_user_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="orcamento",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="projeto",
            name="proposta_recebida",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="user",
            name="comentario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="core.comentario",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="favorito",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="core.favorito",
            ),
        ),
    ]
