# Generated by Django 5.0.6 on 2024-08-13 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_userprojeto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprojeto",
            name="client_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="client_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="userprojeto",
            name="freelancer_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="freelancer_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userprojeto",
            name="projeto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="user_projects", to="core.projeto"
            ),
        ),
    ]
