# Generated by Django 5.0.6 on 2024-12-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_user_area_atuacao_alter_user_telefone"),
    ]

    operations = [
        migrations.AddField(
            model_name="nacionalidade",
            name="cidade",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
