# Generated by Django 5.0.6 on 2024-10-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_rename_avatar_user_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="icon",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
