# Generated by Django 5.0.6 on 2024-10-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_categoria_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
