# Generated by Django 5.0.6 on 2024-12-17 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_projeto_image_project_projeto_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprojeto",
            name="empresa_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="empresa_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userprojeto",
            name="freelancer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="freelancer_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userprojeto",
            name="projeto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="candidatos", to="core.projeto"
            ),
        ),
    ]
