# Generated by Django 5.0.6 on 2024-11-07 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_user_created_at"),
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="status",
            field=models.IntegerField(choices=[(1, "Fechado"), (2, "Em andamento"), (3, "Finalizado")], default=2),
        ),
        migrations.AlterField(
            model_name="user",
            name="foto",
            field=models.ForeignKey(
                blank=True,
                default="media/image/afbe4edb-d9e8-4bd2-b078-8c41f6abea37.png",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="uploader.image",
            ),
        ),
    ]
