# Generated by Django 5.0.6 on 2024-10-30 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_user_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "nivel_academico",
                    models.CharField(
                        choices=[
                            ("fundamental", "Ensino Fundamental"),
                            ("medio", "Ensino Médio"),
                            ("graduacao", "Graduação"),
                            ("pos_graduacao", "Pós-Graduação"),
                            ("mestrado", "Mestrado"),
                            ("doutorado", "Doutorado"),
                        ],
                        max_length=50,
                        verbose_name="Nível Acadêmico",
                    ),
                ),
                ("escola_academica", models.CharField(max_length=255, verbose_name="Instituição de Ensino")),
            ],
            options={
                "verbose_name": "Formação",
                "verbose_name_plural": "Formações",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="comentario",
        ),
        migrations.AddField(
            model_name="user",
            name="rating",
            field=models.FloatField(default=0.0, verbose_name="Média de Avaliações"),
        ),
        migrations.AddField(
            model_name="user",
            name="total_avaliacoes",
            field=models.PositiveIntegerField(default=0, verbose_name="Total de Avaliações"),
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "nota",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 Estrela(s)"),
                            (2, "2 Estrela(s)"),
                            (3, "3 Estrela(s)"),
                            (4, "4 Estrela(s)"),
                            (5, "5 Estrela(s)"),
                        ],
                        verbose_name="Nota",
                    ),
                ),
                ("comentario", models.TextField(blank=True, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "avaliado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes_recebidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "avaliador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes_feitas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
                "unique_together": {("avaliador", "avaliado")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="formacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="core.formacao",
            ),
        ),
        migrations.DeleteModel(
            name="Comentario",
        ),
    ]
