# Generated by Django 5.0.6 on 2024-11-07 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_projeto_status_alter_user_foto"),
        ("core", "0013_formacao_remove_user_comentario_user_rating_and_more"),
    ]

    operations = []
