# Generated by Django 5.0.6 on 2024-11-07 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_merge_20241106_2328"),
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nacionalidade",
            name="sigla",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="user",
            name="foto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="uploader.image",
            ),
        ),
    ]
