# Generated by Django 5.0.6 on 2024-11-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_nacionalidade_sigla_alter_user_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="foto_str",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
