# Generated by Django 5.0.6 on 2024-11-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_user_foto_str"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
