# Generated by Django 5.0.6 on 2024-12-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_user_foto_remove_user_foto_str_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cnpj",
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_empresa",
            field=models.BooleanField(default=False),
        ),
    ]
