# Generated by Django 5.0.6 on 2024-12-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_user_cnpj_user_descricao_user_is_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="isClosed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projeto",
            name="isExpired",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projeto",
            name="max_candidates",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
