# Generated by Django 5.0.6 on 2024-11-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mensagem",
            name="conversa",
        ),
        migrations.RemoveField(
            model_name="mensagem",
            name="remetente",
        ),
        migrations.DeleteModel(
            name="Conversa",
        ),
        migrations.DeleteModel(
            name="Mensagem",
        ),
    ]
